version: '3.1'
services:
  db:
    image: mysql
    container_name: microservice-user-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3307:3306
    volumes:
    - microservice-user-db-data:/var/lib/mysql

volumes:
  microservice-user-db-data: